# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: "Show tasks."
    cmds:
      - "task -a"
    silent: true
  build:
    desc: "Build the project."
    cmds:
      - "go build ./cmd/bump"
  clean:
    desc: "Remove build artifacts."
    cmds:
      - rm bump
  install:
    desc: "Install bump into GOPATH"
    cmds:
      - go install ./cmd/bump
  test:
    desc: "Run tests."
    cmds:
      - go test -cover -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
